In [1]:
import pandas as pd

In [45]:
df = pd.read_csv(r"C:\Users\SOURAV\Downloads\encode (1) (1).csv")

In [46]:
df

ID     Name  Gender  Age    Country Purchased Customer Satisfaction
0   1    Alice  Female   23        USA       Yes        Very Satisfied
1   2      Bob    Male   35     Canada        No               Neutral
2   3  Charlie    Male   45  Australia       Yes             Satisfied
3   4    Diana  Female   28         UK        No          Dissatisfied
4   5    Ethan    Male   30        USA       Yes        Very Satisfied
5   6    Fiona  Female   22     Canada        No     Very Dissatisfied
6   7   George    Male   29  Australia       Yes             Satisfied
7   8   Hannah  Female   33         UK        No               Neutral
8   9      Ian    Male   40        USA       Yes        Very Satisfied
9  10  Jessica  Female   27     Canada        No          Dissatisfied

### ONE HOT ENCODING

In [47]:
from sklearn.preprocessing import OneHotEncoder

In [48]:
ohe = OneHotEncoder(dtype='int', drop='first')
pd.DataFrame(ohe.fit_transform(df[['Gender']]).todense(), columns=ohe.get_feature_names_out())

Gender_Male
0            0
1            1
2            1
3            0
4            1
5            0
6            1
7            0
8            1
9            0

In [49]:
ohe = OneHotEncoder(dtype='int', drop='first')
pd.DataFrame(ohe.fit_transform(df[['Country']]).todense(), columns=ohe.get_feature_names_out())

Country_Canada  Country_UK  Country_USA
0               0           0            1
1               1           0            0
2               0           0            0
3               0           1            0
4               0           0            1
5               1           0            0
6               0           0            0
7               0           1            0
8               0           0            1
9               1           0            0

In [50]:
ohe = OneHotEncoder(dtype='int', drop='first')
pd.DataFrame(ohe.fit_transform(df[['Purchased']]).todense(), columns=ohe.get_feature_names_out())

Purchased_Yes
0              1
1              0
2              1
3              0
4              1
5              0
6              1
7              0
8              1
9              0

In [34]:
car_brand = pd.read_csv(r"C:\Users\SOURAV\Downloads\Car Brand.csv")

In [35]:
car_brand.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### fit()

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(stop_words='english')

In [41]:
df = pd.read_csv(r"C:\Users\SOURAV\Downloads\4743416-text_filess\sample_text.csv")

In [42]:
bow.fit(df['text'])

CountVectorizer(stop_words='english')

In [28]:
bow.fit(df[['text']]).todense()

AttributeError: 'CountVectorizer' object has no attribute 'todense'

In [26]:
bow.vocabulary_

{'data': 2, 'analyst': 1, 'scientist': 5, 'engineer': 3, 'ml': 4, 'ai': 0}

# fit_transform()

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [33]:
ohe.fit_transform(df[['text']]).todense()

matrix([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

# transform()

In [36]:
car_brand.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [38]:
df.head()

ID     Name  Gender  Age    Country Purchased Customer Satisfaction
0   1    Alice  Female   23        USA       Yes        Very Satisfied
1   2      Bob    Male   35     Canada        No               Neutral
2   3  Charlie    Male   45  Australia       Yes             Satisfied
3   4    Diana  Female   28         UK        No          Dissatisfied
4   5    Ethan    Male   30        USA       Yes        Very Satisfied

In [44]:
ohe.transform(df[['text']]).todense()

matrix([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [52]:
ohe.categories_

[array(['No', 'Yes'], dtype=object)]

# Ordinal Encoding

In [55]:
df = pd.read_csv(r"C:\Users\SOURAV\Downloads\encode (1) (1).csv")

In [56]:
df

ID     Name  Gender  Age    Country Purchased Customer Satisfaction
0   1    Alice  Female   23        USA       Yes        Very Satisfied
1   2      Bob    Male   35     Canada        No               Neutral
2   3  Charlie    Male   45  Australia       Yes             Satisfied
3   4    Diana  Female   28         UK        No          Dissatisfied
4   5    Ethan    Male   30        USA       Yes        Very Satisfied
5   6    Fiona  Female   22     Canada        No     Very Dissatisfied
6   7   George    Male   29  Australia       Yes             Satisfied
7   8   Hannah  Female   33         UK        No               Neutral
8   9      Ian    Male   40        USA       Yes        Very Satisfied
9  10  Jessica  Female   27     Canada        No          Dissatisfied

In [57]:
from sklearn.preprocessing import OrdinalEncoder

In [64]:
seq = [['Very Dissatisfied','Dissatisfied','Neutral','Satisfied','Very Satisfied']]
ordinal  = OrdinalEncoder(categories=seq)

In [65]:
ordinal.fit_transform(df[['Customer Satisfaction']])

array([[4.],
       [2.],
       [3.],
       [1.],
       [4.],
       [0.],
       [3.],
       [2.],
       [4.],
       [1.]])

In [66]:
df['Customer Satisfaction'].unique()

array(['Very Satisfied', 'Neutral', 'Satisfied', 'Dissatisfied',
       'Very Dissatisfied'], dtype=object)

In [67]:
ordinal.categories_

[array(['Very Dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied',
        'Very Satisfied'], dtype=object)]

# Missing Values

In [1]:
import pandas as pd

In [22]:
df = pd.read_csv(r"C:\Users\SOURAV\Documents\EDA_INNOMATICS\pandas\Datasets\Data Cleaning\emp_salary.csv")

In [4]:
df.drop(columns='Unnamed: 0', inplace=True)

In [7]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

In [12]:
df['Salary'].fillna(df['Salary'].mean(), inplace=True)

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(drop='first')
df[['Gender']] = ohe.fit_transform(df[['Gender']]).todense()

In [15]:
X = df.drop(columns='Salary')
y = df['Salary']

In [18]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X,y)

ValueError: could not convert string to float: 'Arjun'

# Missing Values in ML Module

### Simple Imputer

In [19]:
from sklearn.impute import SimpleImputer

In [20]:
df

Name   Age  Gender   Salary
0    Arjun  23.0     1.0  42720.0
1   Rajesh  45.0     1.0  23000.0
2   Ramesh   NaN     1.0  45000.0
3   Suresh  48.0     1.0  56000.0
4     Asha  43.0     0.0  55600.0
5  Mounika  27.0     0.0  34000.0
6   Naresh  34.0     1.0  42720.0

In [28]:
mean_imp = SimpleImputer(strategy='mean')
df[['Age']] = mean_imp.fit_transform(df[['Age']])

In [29]:
median_imputer = SimpleImputer(strategy='median')
df[['Salary']] = median_imputer.fit_transform(df[['Salary']])

In [33]:
mode_imputer = SimpleImputer(strategy='most_frequent')
df[['Gender']] = mode_imputer.fit_transform(df[['Gender']])

In [34]:
median_imputer.statistics_

array([45000.])

In [35]:
mode_imputer.statistics_

array(['Male'], dtype=object)

In [36]:
df

Unnamed: 0     Name        Age  Gender   Salary
0           0    Arjun  23.000000    Male  45000.0
1           1   Rajesh  45.000000    Male  23000.0
2           2   Ramesh  36.666667    Male  45000.0
3           3   Suresh  48.000000    Male  56000.0
4           4     Asha  43.000000  Female  55600.0
5           5  Mounika  27.000000  Female  34000.0
6           6   Naresh  34.000000    Male  45000.0

# Feature Transformation

In [37]:
df = pd.read_csv(r"C:\Users\SOURAV\Documents\EDA_INNOMATICS\pandas\Datasets\Distributions.csv")

In [39]:
df.head()

Unnamed: 0  Fearure 1  Feature 2  Feature 3  Feature 4  Feature 5  \
0           0  11.554128 -26.034430  -2.675178   1.274961   2.401627   
1           1   6.524486 -16.982278  -2.144519   1.934269   0.210880   
2           2  13.235726  -7.796441  -2.792420  -0.961317   1.721768   
3           3  29.099671  -4.127851  -2.307962   1.878895   0.786647   
4           4   5.985034 -13.851603  -3.893615  -0.275065   0.081054   

   Feature 6      Feature 7  Feature 8  
0  12.695860      15.390034   1.040080  
1  13.382041     513.897859   2.393011  
2  12.894932  457104.219000   1.286125  
3   8.983775    1022.104024   1.012143  
4  11.610182  214933.717800   1.862475

In [40]:
from sklearn.preprocessing import PowerTransformer

In [44]:
pt = PowerTransformer(method='box-cox')
pt.fit_transform(df[['Fearure 1']])

array([[ 0.50291375],
       [-0.1425586 ],
       [ 0.65403859],
       [ 1.51288114],
       [-0.24143315],
       [-0.24141619],
       [ 1.56700736],
       [ 0.7732711 ],
       [-0.48565839],
       [ 0.54889972],
       [-0.47934429],
       [-0.48175444],
       [ 0.24587582],
       [-2.03432001],
       [-1.8272828 ],
       [-0.5826033 ],
       [-1.05823717],
       [ 0.31906999],
       [-0.94684424],
       [-1.48702394],
       [ 1.45747775],
       [-0.23278047],
       [ 0.06839334],
       [-1.50048954],
       [-0.56387402],
       [ 0.1126593 ],
       [-1.20578102],
       [ 0.38113099],
       [-0.62276462],
       [-0.30094331],
       [-0.62388381],
       [ 1.82838906],
       [-0.01446088],
       [-1.10607696],
       [ 0.82795751],
       [-1.280678  ],
       [ 0.21229173],
       [-2.08554364],
       [-1.39617585],
       [ 0.2001026 ],
       [ 0.74447841],
       [ 0.17419396],
       [-0.11929244],
       [-0.31068814],
       [-1.55875107],
       [-0

# Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [46]:
ss = StandardScaler()
ss.fit_transform(df[['Fearure 1']])

array([[ 2.18786004e-02],
       [-3.47864254e-01],
       [ 1.45497538e-01],
       [ 1.31169993e+00],
       [-3.87520862e-01],
       [-3.87514360e-01],
       [ 1.42264912e+00],
       [ 2.56217815e-01],
       [-4.71496735e-01],
       [ 5.76580288e-02],
       [-4.69550869e-01],
       [-4.70294929e-01],
       [-1.52151280e-01],
       [-7.30419980e-01],
       [-7.12485609e-01],
       [-5.00025969e-01],
       [-6.09188313e-01],
       [-1.06754947e-01],
       [-5.87593567e-01],
       [-6.75115944e-01],
       [ 1.20402955e+00],
       [-3.84191183e-01],
       [-2.50270911e-01],
       [-6.76813098e-01],
       [-4.94706244e-01],
       [-2.27281363e-01],
       [-6.34714286e-01],
       [-6.57709754e-02],
       [-5.11136138e-01],
       [-4.09725709e-01],
       [-5.11440056e-01],
       [ 2.04952005e+00],
       [-2.90865783e-01],
       [-6.17830497e-01],
       [ 3.11324501e-01],
       [-6.46460515e-01],
       [-1.71972342e-01],
       [-7.34389597e-01],
       [-6.6

# Outliers

In [47]:
df = pd.DataFrame({'Marks': [10,20,30,40,50,900,-300]})

In [50]:
df

Marks
0     10
1     20
2     30
3     40
4     50
5    900
6   -300

Library we use for identifying outliers - 'feature_engine'

In [51]:
!pip install feature_engine

In [52]:
from feature_engine.outliers import OutlierTrimmer

In [53]:
outlier = OutlierTrimmer()

In [54]:
outlier.fit_transform(df[['Marks']])

Marks
0     10
1     20
2     30
3     40
4     50
5    900
6   -300

# Missing Values

### a) Constant Value

In [79]:
df = pd.read_csv(r"C:\Users\SOURAV\Documents\EDA_INNOMATICS\pandas\Datasets\Data Cleaning\marks.csv")
df.drop(columns='Unnamed: 0', inplace=True)
import warnings
warnings.filterwarnings('ignore')

In [80]:
df

X      Y
0   1    2.0
1   2    4.0
2   3    NaN
3   4    8.0
4   5   10.0
5  60  120.0

In [81]:
df['Y'].fillna(value=0, inplace=True)

In [82]:
df

X      Y
0   1    2.0
1   2    4.0
2   3    0.0
3   4    8.0
4   5   10.0
5  60  120.0

### b) Statistical Value

In [83]:
df = pd.read_csv(r"C:\Users\SOURAV\Documents\EDA_INNOMATICS\pandas\Datasets\Data Cleaning\marks_missing.csv")
df

Grade  Marks
0     A    NaN
1     A   77.0
2     B   65.0
3     B    NaN
4     C   45.0
5     C   37.0
6     A   88.0
7     B    NaN
8     C   40.0
9     A   95.0

In [84]:
df['Marks'].skew()

np.float64(0.12066614656987014)

In [85]:
df['Marks'].fillna(df['Marks'].mean(), inplace=True)

In [86]:
df

Grade      Marks
0     A  63.857143
1     A  77.000000
2     B  65.000000
3     B  63.857143
4     C  45.000000
5     C  37.000000
6     A  88.000000
7     B  63.857143
8     C  40.000000
9     A  95.000000

### c) Dataset Value

### d) groupby

In [87]:
df = pd.read_csv(r"C:\Users\SOURAV\Documents\EDA_INNOMATICS\pandas\Datasets\Data Cleaning\marks_missing.csv")

In [88]:
df

Grade  Marks
0     A    NaN
1     A   77.0
2     B   65.0
3     B    NaN
4     C   45.0
5     C   37.0
6     A   88.0
7     B    NaN
8     C   40.0
9     A   95.0

In [91]:
df['Marks'] = round(df.groupby(by='Grade')['Marks'].transform(lambda x: x.fillna(x.mean())))

In [92]:
df

Grade  Marks
0     A   87.0
1     A   77.0
2     B   65.0
3     B   65.0
4     C   45.0
5     C   37.0
6     A   88.0
7     B   65.0
8     C   40.0
9     A   95.0

### e) Interpolate

In [93]:
import numpy as np

In [95]:
df = pd.DataFrame({'X': [10,20,30,40,50,60],
                  'Y': [np.nan, 20000,30000,np.nan,50000,60000]})

In [96]:
df

X        Y
0  10      NaN
1  20  20000.0
2  30  30000.0
3  40      NaN
4  50  50000.0
5  60  60000.0

In [97]:
df.interpolate(method='linear')

X        Y
0  10      NaN
1  20  20000.0
2  30  30000.0
3  40  40000.0
4  50  50000.0
5  60  60000.0